import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_ui/Header";
import DataProvider from "./context/DataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-dvh grid grid-rows-[auto_1fr]`}
      >
        <DataProvider>
          <Header />
          <main className="bg-stone-100">{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
